#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
if [ $# -gt 3 ]; then
    scp -o StrictHostKeyChecking=no -i ~/.ssh/school $1 ubuntu@$2:~/
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
